import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  main: [
    'intro',
    {
      type: 'category',
      label: 'Java',
      items: [{type: 'autogenerated', dirName: 'java'}],
    },
    {
      type: 'category',
      label: 'Spring Ecosystem',
      items: [{type: 'autogenerated', dirName: 'spring'}],
    },
    {
      type: 'category',
      label: 'Testing & Mocking',
      items: [{type: 'autogenerated', dirName: 'testing'}],
    },
    {
      type: 'category',
      label: 'Design Patterns',
      items: [{type: 'autogenerated', dirName: 'design-patterns'}],
    },
    {
      type: 'category',
      label: 'SOLID Principles',
      items: [{type: 'autogenerated', dirName: 'solid'}],
    },
    {
      type: 'category',
      label: 'System Design',
      items: [{type: 'autogenerated', dirName: 'system-design'}],
    },
    {
      type: 'category',
      label: 'Coding Interview Prep',
      items: [{type: 'autogenerated', dirName: 'coding-interview'}],
    },
    {
      type: 'category',
      label: 'Security',
      items: [{type: 'autogenerated', dirName: 'security'}],
    },
    {
      type: 'category',
      label: 'Networking',
      items: [{type: 'autogenerated', dirName: 'networking'}],
    },
    {
      type: 'category',
      label: 'Kafka',
      items: [{type: 'autogenerated', dirName: 'kafka'}],
    },
    {
      type: 'category',
      label: 'Database',
      items: [{type: 'autogenerated', dirName: 'database'}],
    },
    {
      type: 'category',
      label: 'Redis',
      items: [{type: 'autogenerated', dirName: 'redis'}],
    },
    {
      type: 'category',
      label: 'Operating Systems',
      items: [{type: 'autogenerated', dirName: 'operating-systems'}],
    },
    {
      type: 'category',
      label: 'Git & Version Control',
      items: [{type: 'autogenerated', dirName: 'git'}],
    },
    {
      type: 'category',
      label: 'DevOps & Containerization',
      items: [{type: 'autogenerated', dirName: 'devops'}],
    },
    {
      type: 'category',
      label: 'AWS',
      items: [{type: 'autogenerated', dirName: 'aws'}],
    },
    {
      type: 'category',
      label: 'Banking & Finance',
      items: [{type: 'autogenerated', dirName: 'banking-finance'}],
    },
    {
      type: 'category',
      label: 'Books',
      items: [{type: 'autogenerated', dirName: 'books'}],
    },
    {
      type: 'category',
      label: 'Interview Questions',
      items: [{type: 'autogenerated', dirName: 'interview-questions'}],
    },
    {
      type: 'category',
      label: 'SDLC',
      items: [{type: 'autogenerated', dirName: 'sdlc'}],
    },
  ],
};

export default sidebars;
