import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Autogenerated: any new file/folder under docs/ is automatically picked up.
// Use _category_.json files inside docs/<folder>/ to control labels and ordering.
const sidebars: SidebarsConfig = {
  main: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
